### ISSUE TITLE
What is Service Mesh

### ISSUE THREAD

**Issue by joelbyronbarker** [aijamalnk/istio.io#10]
It includes:
- What is Istio?
- What Is service mesh?
- Istio vs X, Y, Z
- Key considerations

**Comment by craigbox** [comment]
James Brook, a Googler working with bol.com, has had a quick look; he's going to do a full review on Monday 1 Feb.

**Comment by joelbyronbarker** [comment]
> James Brook, a Googler working with bol.com, has had a quick look; he's going to do a full review on Monday 1 Feb.

I think this should be a comment on the bol.com issue? https://github.com/aijamalnk/istio.io/issues/5

**Comment by craigbox** [comment]
Good spotting

**Comment by joelbyronbarker** [comment]
Version one for review to @craigbox  https://docs.google.com/document/d/1YvWVJVoamjnLueFGKXgGZ-nvpFEEdskr9ucGTneogTA/edit

**Comment by joelbyronbarker** [comment]
I evaluated the content to confirm that it is usable in a dual purpose to also provide awareness for business readers. I made some comments that we will apply in v2 upon completion of the review. FYI @aijamalnk @craigbox

**Comment by joelbyronbarker** [comment]
It does not seem to have been captured in the requirements, but I wanted to note that "Istio vs. X, Y, Z" is something that most software orgs avoid doing as it means you have to then track the feature releases of X, Y, and Z forever and change those differentiators as they release new features.

**Comment by joelbyronbarker** [comment]
Current status:
Some commentary by steering members, but no checks in the review boxes. Srinath has asked Lions to go through and address comments that are currently in place.

**Comment by joelbyronbarker** [comment]
Current status: By request from Craig and Srinath, Lions have addressed all comments and changes. 31 March 2021. https://docs.google.com/document/d/1YvWVJVoamjnLueFGKXgGZ-nvpFEEdskr9ucGTneogTA/edit Next step: Craig and Sri pilot approval or any additional changes.
