### ISSUE TITLE
Copy for Get Involved page

### ISSUE THREAD

**Issue by aijamalnk** [aijamalnk/istio.io#12]
**[Version 1 for review](https://docs.google.com/document/d/1riO0hzjx3or9l6YaR-OoFDJjUigUGJEsMZ0MfjXngrM/edit)** 

@joelbyronbarker we talked about writing copy for the Get Involved page. Polidea is developing it, and you can see a preview here: https://github.com/aijamalnk/istio.io-design-and-dev/issues/6

We'll need content for it, and we can use the current Istio.io Get Involved page (you can find those links in the comments for https://github.com/aijamalnk/istio.io-design-and-dev/issues/6).

**Comment by joelbyronbarker** [comment]
I see this! We are on it.

**Comment by joelbyronbarker** [comment]
@craigbox I know you are hip deep in Istiocon. In the mean time here is the Get Involved copy. FYI @aijamalnk https://docs.google.com/document/d/1riO0hzjx3or9l6YaR-OoFDJjUigUGJEsMZ0MfjXngrM/edit?usp=drive_web&ouid=105471892726675923117

**Comment by joelbyronbarker** [comment]
Status 31 March 2021: As per the request by Srinath and Craig, Lion's Way addressed changes and comments. 
This is ready for a review to either approve or signal more changes. https://docs.google.com/document/d/1riO0hzjx3or9l6YaR-OoFDJjUigUGJEsMZ0MfjXngrM/edit?usp=drive_web&ouid=105471892726675923117

**Comment by srithreepo** [comment]
Added comments inline looks great.
