### ISSUE TITLE
Short text for multiple pages

### ISSUE THREAD

**Issue by joelbyronbarker** [aijamalnk/istio.io#13]
Text, as requested, for multiple pages. Mainly the first introductory text after the first header or page title.

https://docs.google.com/document/d/17WKsGbow42T82Q1d_f-Z8-aGsQoWgVxEb__Mwgq5Lwk/edit?usp=sharing

**Comment by craigbox** [comment]
Srinath isn't available for assignation, but this is now with him as my comments have been addressed.

**Comment by srithreepo** [comment]
LGTM subject to few comments on the doc itself. only one major comment,
