### ISSUE TITLE
Auto Trader Case Study

### ISSUE THREAD

**Issue by joelbyronbarker** [aijamalnk/istio.io#3]
Version 2: https://docs.google.com/document/d/1RLaMETDScXDz4ovxJd9mkto3GhQFPDldVF9KdWGagI8/edit

**Comment by craigbox** [comment]
My comments are in; added Doug Reid, John Howard at Istio team suggestion, and Srinath, for comments before handing to round 2.

**Comment by joelbyronbarker** [comment]
Thanks so much! For efficiency and consistency, we will look at all the changes once you assign this issue to me, @craigbox. That way we know that all the input is in, you have what you need to know what approval looks like, and we can move on to v2.

**Comment by craigbox** [comment]
There's enough feedback in there to move to Round 2 without Srinath needing to review.

There was some important context that we think is relevant and was missed - probably Karl Stoney didn't mention it on the call - but you can look at the Twitter thread that John linked, and Doug's comments, to get the bulk of it.

**Comment by joelbyronbarker** [comment]
Great! Know that we won't want to take feedback from Srinath on v2 if he does not see v1. We will get started.

**Comment by joelbyronbarker** [comment]
@craigbox We have produced v2. Left the GDPR comments in there because we wanted to make sure we addressed it. Did we cover that comment?
