### ISSUE TITLE
Questionnaire for Solution Guides

### ISSUE THREAD

**Issue by joelbyronbarker** [aijamalnk/istio.io#8]
(Will not go through review process)

**Comment by joelbyronbarker** [comment]
We have received input from Craig and from our internal team. This form is ready to use.

**Comment by aijamalnk** [comment]
UPDATE:
1. Lions is to create the questionnaire (linked in that issue)
2. @craigbox is to write the content into it. The questionnaire is to help with headings and styles, to make sure they are consistent and that fit into the page, etc.

**Comment by aijamalnk** [comment]
3. @joelbyronbarker will copy-edit the final draft provided by @craigbox
