### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by joelbyronbarker** [aijamalnk/istio.io#9]
Follow Figma.

The clean version to deliver to the web team: https://docs.google.com/document/d/1HODNkyOSDQ3p13UDv5FC7F1G6qBtp8FB1H1AEESGP84/edit?usp=sharing

**Comment by joelbyronbarker** [comment]
Awaiting confirmation that the design is finalized. We expect that February 2.

**Comment by joelbyronbarker** [comment]
Version 1 Copy for Review by @craigbox and company: https://docs.google.com/document/d/1A69d9Gx--fhed-C2L866Nect1VYpZCor7w5ydP97AGg/edit?usp=sharing

**Comment by craigbox** [comment]
Enough time and reviewers have passed that I'm happy to go to round 2 on this.

**Comment by joelbyronbarker** [comment]
Version 2 for review: Clean: version to deliver to web team: https://docs.google.com/document/d/1HODNkyOSDQ3p13UDv5FC7F1G6qBtp8FB1H1AEESGP84/edit?usp=sharing

markup version for accounting changes with previous comments: https://drive.google.com/file/d/1Ssn8CDzzj06UVGlN_uVElOVkhizCEfnR/view?usp=sharing

**Comment by joelbyronbarker** [comment]
Current status:
V2-01-working is the working copy. I have two open questions in comments. https://docs.google.com/document/d/1HODNkyOSDQ3p13UDv5FC7F1G6qBtp8FB1H1AEESGP84/edit# 

Craig has made a clean copy which has additional changes he made, a branch.

**Comment by joelbyronbarker** [comment]
Craig's version has been merged into the working copy: https://docs.google.com/document/d/1HODNkyOSDQ3p13UDv5FC7F1G6qBtp8FB1H1AEESGP84/edit# 

31 March 2021: All issues have been addressed by Lion's Way. The last section was a complete change based on the Tuesday meeting. Link directly to that section for your convenience: https://docs.google.com/document/d/1HODNkyOSDQ3p13UDv5FC7F1G6qBtp8FB1H1AEESGP84/edit?disco=AAAALv1Wen0 

Status: Awaiting approval or further input. At that point we will create a clean copy without the greyed out/crossed out sections.
